on:
  workflow_dispatch:

jobs:
  generate-inventory:
    runs-on: [ ]

    steps:
     

      - name: Create inventory directory
        run: |
          sudo -u shruti mkdir -p /home/shruti/ansible/
          sudo chown -R shruti:shruti /home/shruti/ansible

      - name: Generate inventory.yaml
        run: |
          sudo -u shruti bash -c 'cat > /home/shruti/ansible/inventory.yaml' << 'EOF'
          ---
          all:
            children:
              webservers:
                hosts:
                  web01:
                    ansible_host: 10.204.0.10
                    ansible_user: user20
                    

              databases:
                hosts:
                  db01:
                    ansible_host: 10.204.0.6
                    ansible_user: user20
                    db_version: 14
                   

              
          EOF
